name: card_rec_env
channels:
  - defaults
dependencies:
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.9.12
  - readline=8.1.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tk=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - algo-ops
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bidict==0.22.0
    - black==22.3.0
    - bleach==5.0.0
    - cffi==1.15.0
    - charset-normalizer==2.0.12
    - click==8.1.3
    - commonmark==0.9.1
    - cycler==0.11.0
    - dacite==1.6.0
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docutils==0.18.1
    - easyocr==1.5.0
    - entrypoints==0.4
    - executing==0.8.3
    - ezplotly
    - fastjsonschema==2.15.3
    - fonttools==4.33.3
    - idna==3.3
    - imageio==2.19.3
    - importlib-metadata==4.11.4
    - ipykernel==6.13.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.0
    - jupyter==1.0.0
    - jupyter-client==7.3.1
    - jupyter-console==6.4.3
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kaleido==0.2.1
    - keyring==23.5.1
    - kiwisolver==1.4.2
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - natsort==8.1.0
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==2.8.2
    - nose==1.3.7
    - notebook==6.4.11
    - numpy==1.22.4
    - ocr-ops
    - opencv-python-headless==4.5.4.60
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - pkginfo==1.8.2
    - platformdirs==2.5.2
    - plotly==5.8.0
    - pokemontcgsdk==3.4.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.12.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pyspellchecker==0.6.3
    - pytesseract==0.3.9
    - python-bidi==0.4.2
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.1.0
    - qtconsole==5.3.0
    - qtpy==2.1.0
    - readme-renderer==35.0
    - requests==2.27.1
    - requests-toolbelt==0.9.1
    - rfc3986==2.0.0
    - rich==12.4.4
    - scikit-image==0.19.2
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - send2trash==1.8.0
    - shapely==1.8.2
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - tenacity==8.0.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tifffile==2022.5.4
    - tinycss2==1.1.1
    - tomli==2.0.1
    - torch==1.11.0
    - torchvision==0.12.0
    - tornado==6.1
    - traitlets==5.2.2.post1
    - twine==4.0.1
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - zipp==3.8.0